name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        # run: ./build-scripts.bash 
        run: |
          mkdir ./dist
          echo "hello world" > ./dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.5.4-5
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          allow_empty_commit: true
